// ignore_for_file: file_names


//? O QUE É SERVIÇO REST
//? É UMA TROCA DE INFORMAÇÕES ENTRE SISTEMAS UTILIZANDO O PROTOCOLO HTTP

//? CARACTERISTICAS DE SERVIÇO REST  CLIENTE-SERVIDOR
//? SERVIÇO REST É STATELESS NAO MANTEM ESTADO 

//! UM SERVIÇO RETFULL POSSUI UM 'URI' PARA CADA ITEM NO INVENTARIO

